---
- name: Server
  hosts: servers
  become: true
  roles:
    - server
- name: Web Servers
  hosts: webs
  become: true
  roles:
    - web
- name: APIs
  hosts: apis
  become: true
  roles:
    - api
- name: Generator
  hosts: gens
  become: true
  roles:
    - gen