---
- name: Install Node
  dnf:
    name: "@nodejs:16"
    update_cache: yes
- name: Copy files
  copy:
    src: "../../../../../api/{{ item }}"
    dest: /home/opc/api/
    owner: opc
  with_items:
  - "api.js"
  - "package.json"
  - "package-lock.json"
- name: Copy env file
  template:
    src: ../files/env.j2
    dest: /home/opc/api/.env
    owner: opc
    group: opc
    mode: 0640
- name: Install dependencies
  command: npm install
  become: true
  become_user: opc
  args:
    chdir: /home/opc/api/
- name: Install pm2
  command: npm install pm2 -g
- name: Add firewall port 3000
  firewalld:
    zone: public
    port: 3000/tcp
    permanent: yes
    immediate: yes
    state: enabled
- name: Daemonized pm2
  command: "pm2 list"
  become: true
  become_user: opc
- name: Register running apps
  command: "pm2 list --mini-list"
  become: true
  become_user: opc
  register: num_instances
- name: PRINT DEBUG
  debug:
    msg: "{{ num_instances.stdout_lines }}"
- name: Reload
  command: pm2 reload --update-env api
  become: true
  become_user: opc
  when: num_instances.stdout_lines | length > 0
  environment:
    NODE_ENV: production
  args:
    chdir: /home/opc/api/
- name: Run
  command: pm2 start api.js -i {{ api_instances_per_node }}
  become: true
  become_user: opc
  when: num_instances.stdout_lines | length == 0
  environment:
    NODE_ENV: production
  args:
    chdir: /home/opc/api/