---
- name: Install NGINX and Node
  dnf:
    name: "@nodejs:16"
    update_cache: yes
- name: Copy server files
  copy:
    src: "../../../../../server/{{ item }}"
    dest: /home/opc/server/
    owner: opc
  with_items:
  - "src/app.js"
  - "package.json"
  - "package-lock.json"
- name: Copy env file
  template:
    src: ../files/env.j2
    dest: /home/opc/server/.env
    owner: opc
    group: opc
    mode: 0744
- name: Install dependencies
  command: npm install
  become: true
  become_user: opc
  args:
    chdir: /home/opc/server/
- name: Install pm2
  command: npm install pm2 -g
- name: Run WebSocket Server
  command: pm2 --node-args="--max-old-space-size=512" -f start app.js
  become: true
  become_user: opc
  args:
    chdir: /home/opc/server/
- name: Add firewall port 3000
  firewalld:
    zone: public
    port: 3000/tcp
    permanent: yes
    immediate: yes
    state: enabled